spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studiopick
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

aws:
  s3:
    bucket: studiopick-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
